### ISSUE TITLE
report bug 

### ISSUE THREAD

**Issue by SueeH** [NERanger/auto_lidar_cam_calib#1]
in InverseDistTransform fuc,  out is CV_32FC1, but using out.at<uchar> to get and assign data;
also，in CalibrationTrack，I think GenGridIsometry3f should be initialized in for loop(with iter)，otherwise, the iter may no sense, please check!
Thanks for your code

**Comment by NERanger** [comment]
Thanks for pointing these bugs out ! 

I will get my hands on them ASAP.

**Comment by NERanger** [comment]
The bug in CalibrationTrack is fixed in commit f0718c99faa4d7c00798559280064bc9ae9803f5.

For the one in `InverseDistTransform`, the `at` is used for accessing pixel value in `edge_img` which is a 8UC1 matrix. https://github.com/NERanger/auto_lidar_cam_calib/blob/f0718c99faa4d7c00798559280064bc9ae9803f5/src/Core.cc#L107

The `out` matrix is modified with float pointer.
https://github.com/NERanger/auto_lidar_cam_calib/blob/f0718c99faa4d7c00798559280064bc9ae9803f5/src/Core.cc#L109

**Comment by SueeH** [comment]
> The bug in CalibrationTrack is fixed in commit [f0718c9](https://github.com/NERanger/auto_lidar_cam_calib/commit/f0718c99faa4d7c00798559280064bc9ae9803f5).
> 
> For the one in `InverseDistTransform`, the `at` is used for accessing pixel value in `edge_img` which is a 8UC1 matrix.
> 
> https://github.com/NERanger/auto_lidar_cam_calib/blob/f0718c99faa4d7c00798559280064bc9ae9803f5/src/Core.cc#L107
> 
> The `out` matrix is modified with float pointer.
> 
> https://github.com/NERanger/auto_lidar_cam_calib/blob/f0718c99faa4d7c00798559280064bc9ae9803f5/src/Core.cc#L109

I mean the single thread(although not used).

      const uchar& edge_val = edge_img.at<uchar>(row, col);
      uchar& out_val = out.at<uchar>(row, col);
      out_val = alpha * edge_val + (1.0f - alpha) * ComputeMaxTermInInverseTransform(edge_img, cv::Point2i(col, row));
